apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: gcr.io/myauthapp-376308/myauthapp:7
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-svc
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
