apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-auth-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-auth-app
  template:
    metadata:
      labels:
        app: my-auth-app
    spec:
      containers:
      - name: my-auth-app
        image: gcr.io/myauthapp-376308/myauthapp:7
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: my-auth-app-svc
spec:
  selector:
    app: my-auth-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
